//
//  Item.swift
//  iShnakiOS
//
//  Created by Huw Williams on 07/04/2025.
//

// the name of the file and the class was generated by XCode.
import Foundation
import SwiftData

// MARK: - Models

// Stores user activity and consumption data for a specific day
@Model
final class UserData {
    @Attribute(.unique) var date: Date  // Unique identifier for the day
    
    // Actual consumption and activity metrics
    var caloriesConsumed: Int
    var beverageCalories: Int
    var mealCalories: Int
    var snackCalories: Int
    var stepsTaken: Int
    var amountofWater: Int
    var amountofBeverage: Int
    var amountofSnack: Int
    var amountofMeal: Int
    
    // Default initializer sets all values to zero and uses today’s date
    init() {
        self.date = Calendar.current.startOfDay(for: Date())
        self.caloriesConsumed = 0
        self.beverageCalories = 0
        self.mealCalories = 0
        self.snackCalories = 0
        self.amountofWater = 0
        self.stepsTaken = 0
        self.amountofBeverage = 0
        self.amountofSnack = 0
        self.amountofMeal = 0
    }
}

// Extension for querying only today’s data using a SwiftData predicate
extension UserData {
    static func todayPredicate() -> Predicate<UserData> {
        let calendar = Calendar.current
        let startOfToday = calendar.startOfDay(for: Date())
        let startOfTomorrow = calendar.date(byAdding: .day, value: 1, to: startOfToday)!

        return #Predicate<UserData> { data in
            data.date >= startOfToday && data.date < startOfTomorrow
        }
    }
}

// Stores the user's default health and dietary goals
@Model
final class GoalDefaults {
    var calorieGoal: Int
    var mealGoal: Int
    var snackGoal: Int
    var BeverageGoal: Int
    var waterGoal: Int
    var cupSize: Int
    var waterBottleSize: Int
    var beverageSize: Int
    var mealSize: Int
    var snackSize: Int
    var stepGoal: Int

    // Default initializer sets all goals and sizes to 0
    init() {
        calorieGoal = 0                // Daily calorie goal
        waterGoal = 0                  // Water intake goal
        cupSize = 0                    // Size of one cup of water
        mealGoal = 0                   // Meals per day
        snackGoal = 0                  // Snacks per day
        BeverageGoal = 0              // Beverages per day
        waterBottleSize = 0           // Size of water bottle
        beverageSize = 0              // Size of beverage serving
        mealSize = 0                  // Calories per meal
        snackSize = 0                 // Calories per snack
        stepGoal = 0                  // Steps goal (e.g. 10,000 steps)
    }
}

// Stores the user’s notification preferences
@Model
final class UserNotificationSettings {
    var breakfastHour: Int
    var breakfastMin: Int
    var breakfastBool: Bool

    var lunchHour: Int
    var lunchMin: Int
    var lunchBool: Bool

    var dinnerHour: Int
    var dinnerMin: Int
    var dinnerBool: Bool

    var waterReminder: Int
    var waterReminderBool: Bool

    // Default notification times and toggles
    init () {
        breakfastHour = 8          // 8:00 AM
        breakfastMin = 0
        lunchHour = 13             // 1:30 PM
        lunchMin = 30
        dinnerHour = 18            // 6:00 PM
        dinnerMin = 0
        waterReminder = 120        // Every 2 hours
        breakfastBool = false
        lunchBool = false
        dinnerBool = false
        waterReminderBool = false
    }
}

func seedUserData(context: ModelContext) {
    let calendar = Calendar.current
    let today = calendar.startOfDay(for: Date())

    for dayOffset in 1...30 {
        let date = calendar.date(byAdding: .day, value: -dayOffset, to: today)!
        let userData = UserData()
        userData.date = date
        userData.amountofWater = Int.random(in: 1000...3000)
        userData.amountofBeverage = Int.random(in: 200...1000)
        userData.amountofMeal = Int.random(in: 2...4)
        userData.amountofSnack = Int.random(in: 1...3)
        userData.stepsTaken = Int.random(in: 1000...10000)
        userData.amountofMeal = Int.random(in: 2...4)
        userData.mealCalories = userData.amountofMeal * Int.random(in: 400...700)
        userData.snackCalories = userData.amountofSnack * Int.random(in: 100...300)
        userData.beverageCalories = userData.amountofBeverage / 10
        userData.caloriesConsumed = userData.mealCalories + userData.snackCalories + userData.beverageCalories

        context.insert(userData)
    }

    do {
        try context.save()
        print("Seeded 30 days of UserData.")
    } catch {
        print("Failed to seed UserData: \(error)")
    }
}
