//
//  Item.swift
//  iShnakiOS
//
//  Created by Huw Williams on 07/04/2025.
//

// the name of the file and the class was generated by XCode.
import Foundation
import SwiftData

// MARK: - Models
@Model
final class UserData {
    @Attribute(.unique) var date: Date
    // Actuals
    var caloriesConsumed: Int
    var beverageCalories: Int
    var mealCalories: Int
    var snackCalories: Int
    var stepsTaken: Int
    var amountofWater: Int
    var amountofBeverage: Int
    var amountofSnack: Int
    var amountofMeal: Int
    
    init() {
        
        self.date = Calendar.current.startOfDay(for: Date())
        self.caloriesConsumed = 0
        self.beverageCalories = 0
        self.mealCalories = 0
        self.snackCalories = 0
        self.amountofWater = 0
        self.stepsTaken = 0
        self.amountofBeverage = 0
        self.amountofSnack = 0
        self.amountofMeal = 0
    }
}

@Model
final class GoalDefaults {
    var calorieGoal: Int
    var mealGoal: Int
    var snackGoal: Int
    var BeverageGoal: Int
    var waterGoal: Int
    var cupSize: Int
    var waterBottleSize: Int
    var beverageSize: Int
    var mealSize: Int
    var snackSize: Int
    var stepGoal: Int
    
    init() {
        calorieGoal = 2000 // daily intake of an adult
        waterGoal = 4 // amount of glasses/bottles drunk in a day
        cupSize = 250 // the size of the water container
        mealGoal = 3 // breakfast/lunch/dinner
        snackGoal = 2 // amount of snacks in a day
        BeverageGoal = 2 // amount of coffee/soda in a day/
        waterBottleSize = 600 // waterbootle size
        beverageSize = 270
        mealSize = 450 
        snackSize = 270 // calories
        stepGoal = 5000 // this is half the recommended daily step goal.
        
    }
}








